import Navbar from './components/Navbar'
import { DarkModeProvider } from './context/DarkModeContext'
import { roboto, poppins } from './utils/fonts'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.className} ${poppins.className}`}>
      <body>
        <DarkModeProvider>
          <Navbar />
        </DarkModeProvider>
        {children}
      </body>
    </html>
  )
}
